[2020-02-04 05:08:38,500] [1404-MainProcess/15200-Thread-5] ERROR - SMARTCANTEEN require_authenticate() error=(pyodbc.OperationalError) ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: An existing connection was forcibly closed by the remote host.\r\n (10054) (SQLExecDirectW); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (10054)')
[SQL: SELECT TOP 1 t_session.id AS t_session_id, t_session.factory_id AS t_session_factory_id, t_session.created AS t_session_created, t_session.modified AS t_session_modified, t_session.upd_count AS t_session_upd_count, t_session.note AS t_session_note, t_session.[key] AS t_session_key, t_session.user_id AS t_session_user_id, t_session.expired AS t_session_expired 
FROM t_session 
WHERE t_session.[key] = ? AND t_session.expired > ?]
[parameters: ('9999bf25f476-4552-4337-8c9e-8c96e15a47b8', datetime.datetime(2020, 2, 4, 5, 8, 38, 478843))]
(Background on this error at: http://sqlalche.me/e/e3q8) tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\auth.py", line 40, in require_authenticate\n    user_info = Auth.api_authenticate(db_agent, request.cookies[Session.AUTH_SESSION_KEY], Session.TIMEOUT)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\commonlib\\auth.py", line 23, in api_authenticate\n    session_info = TSessionSql.get_session(db_agent, session_key)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\commonlib\\sql.py", line 69, in get_session\n    session_info = db.session.query(TSession) \\\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3265, in first\n    ret = list(self[0:1])\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3043, in __getitem__\n    return list(res)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3367, in __iter__\n    return self._execute_and_instances(context)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3392, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 982, in execute\n    return meth(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n']
[2020-02-04 05:09:00,215] [1404-MainProcess/480-Thread-7] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
