[2020-02-06 13:40:21,589] [12528-MainProcess/10476-Thread-3] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 13:43:08,013] [14688-MainProcess/4284-Thread-3] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 13:43:20,106] [14688-MainProcess/7400-Thread-4] WARNING - SMARTCANTEEN serving_post() InvalidParamError-factory_id = 0 is not match with user.factory_id (1)
[2020-02-06 13:43:36,042] [14688-MainProcess/4180-Thread-6] WARNING - SMARTCANTEEN serving_post() ConflictError-serving id = 1
[2020-02-06 13:59:22,299] [14248-MainProcess/11428-Thread-4] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 14:00:25,121] [5716-MainProcess/4284-Thread-1] WARNING - SMARTCANTEEN shift_meal_post() InvalidParamError-shift_meal.meal_id is not existing
[2020-02-06 14:00:42,658] [5716-MainProcess/5800-Thread-3] WARNING - SMARTCANTEEN shift_meal_post() InvalidParamError-factory_id = 2 is not match with user.factory_id (1)
[2020-02-06 16:46:53,800] [3652-MainProcess/13040-Thread-4] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 16:47:04,174] [3652-MainProcess/7552-Thread-6] WARNING - SMARTCANTEEN staff_serving_register_post() InvalidParamError-shift_meal_id=1, serving_id=5 is not exist
[2020-02-06 16:47:14,850] [3652-MainProcess/10044-Thread-8] WARNING - SMARTCANTEEN staff_serving_register_post() InvalidParamError-shift_meal_id=1, serving_id=5 is not exist
[2020-02-06 17:05:46,536] [9364-MainProcess/6620-Thread-52] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 18:44:57,447] [4884-MainProcess/6048-Thread-4] WARNING - SMARTCANTEEN require_authenticate() AuthenticateError-CommonLibError-Invalid Session Key
[2020-02-06 18:45:06,994] [4884-MainProcess/6960-Thread-5] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 18:45:12,141] [4884-MainProcess/1756-Thread-6] ERROR - SMARTCANTEEN shift_meal_serving_post() error='EditShiftMealServing' object has no attribute 'serving_list' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 75, in shift_meal_serving_post\n    cls.__ensure_shift_meal_serving_request(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 211, in __ensure_shift_meal_serving_request\n    if shift_meal_serving.serving_list is None:\n']
[2020-02-06 18:45:50,867] [3880-MainProcess/9004-Thread-6] ERROR - SMARTCANTEEN shift_meal_serving_post() error='EditShiftMealServing' object has no attribute 'serving_list' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 75, in shift_meal_serving_post\n    cls.__ensure_shift_meal_serving_request(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 211, in __ensure_shift_meal_serving_request\n    if shift_meal_serving.serving_list is None:\n']
[2020-02-06 18:48:04,072] [5004-MainProcess/6032-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_post() error='ShiftMealServing' object has no attribute 'serving_list' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 75, in shift_meal_serving_post\n    cls.__ensure_shift_meal_serving_request(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 211, in __ensure_shift_meal_serving_request\n    if shift_meal_serving.serving_list is None:\n']
[2020-02-06 18:48:47,625] [10112-MainProcess/4824-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_post() error='ShiftMealServing' object is not iterable tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 75, in shift_meal_serving_post\n    cls.__ensure_shift_meal_serving_request(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 214, in __ensure_shift_meal_serving_request\n    for item in shift_meal_serving:\n']
[2020-02-06 18:50:11,038] [7228-MainProcess/3292-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_post() error='ServingInfo' object has no attribute 'serving_id' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 75, in shift_meal_serving_post\n    cls.__ensure_shift_meal_serving_request(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 215, in __ensure_shift_meal_serving_request\n    cls.__ensure_serving_request(db, item, factory_id)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 227, in __ensure_serving_request\n    if serving_info.serving_id is None:\n']
[2020-02-06 18:51:13,060] [9872-MainProcess/4072-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_post() error='int' object has no attribute 'session' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 75, in shift_meal_serving_post\n    cls.__ensure_shift_meal_serving_request(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 215, in __ensure_shift_meal_serving_request\n    cls.__ensure_serving_request(db, item, factory_id)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 230, in __ensure_serving_request\n    if not ServingSql.is_serving_existing(serving_info.id, factory_id):\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\sql.py", line 1037, in is_serving_existing\n    query = db.session.query(MServing).filter(MServing.id == id)\n']
[2020-02-06 18:52:42,130] [1444-MainProcess/9712-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_post() error='ShiftMealServing' object has no attribute 'id' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 79, in shift_meal_serving_post\n    cls.__execute_shift_meal_serving_post(db, shift_meal_serving)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 95, in __execute_shift_meal_serving_post\n    for serving in shift_meal_serving.id:\n']
[2020-02-06 18:54:59,314] [3288-MainProcess/8388-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_post() error=(pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'serving_id', table 'SMARTCANTEEN.dbo.m_shift_meal_serving'; column does not allow nulls. INSERT fails. (515) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")
[SQL: INSERT INTO m_shift_meal_serving (id, shift_meal_id, serving_id, factory_id, created, modified, name, upd_count, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (1, 1, None, 1, None, None, 'factory1-shift1-START mealstring', None, None)]
(Background on this error at: http://sqlalche.me/e/gkpj) tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 80, in shift_meal_serving_post\n    db.commit()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\commonlib\\db.py", line 82, in commit\n    self.session.commit()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1036, in commit\n    self.transaction.commit()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 503, in commit\n    self._prepare_impl()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 482, in _prepare_impl\n    self.session.flush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2479, in flush\n    self._flush(objects)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2577, in _flush\n    flush_context.execute()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 422, in execute\n    rec.execute(self)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 586, in execute\n    persistence.save_obj(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 1084, in _emit_insert_statements\n    c = cached_connections[connection].execute(statement, multiparams)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 982, in execute\n    return meth(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n']
[2020-02-06 19:11:39,078] [8684-MainProcess/4720-Thread-1] WARNING - SMARTCANTEEN require_authenticate() AuthenticateError-CommonLibError-Invalid Session Key
[2020-02-06 19:11:45,320] [8684-MainProcess/3020-Thread-2] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 19:11:53,046] [8684-MainProcess/676-Thread-3] WARNING - SMARTCANTEEN shift_meal_serving_post() ConflictError-shift_meal_serving  with id = <commonlib.db.DbAccess object at 0x000002CFF5B72C40> is existing
[2020-02-06 19:18:36,058] [5028-MainProcess/356-Thread-1] WARNING - SMARTCANTEEN require_authenticate() AuthenticateError-CommonLibError-Invalid Session Key
[2020-02-06 19:18:42,246] [5028-MainProcess/4328-Thread-2] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 19:18:45,881] [5028-MainProcess/5700-Thread-3] WARNING - SMARTCANTEEN shift_meal_serving_post() ConflictError-shift_meal_serving  with id = 1 is existing
[2020-02-06 19:19:49,911] [5028-MainProcess/9712-Thread-5] WARNING - SMARTCANTEEN shift_meal_serving_post() InvalidParamError-serving id = 10 is None
[2020-02-06 19:20:37,811] [5028-MainProcess/5040-Thread-7] WARNING - SMARTCANTEEN shift_meal_serving_post() InvalidParamError-serving id = 10 is None
[2020-02-06 19:20:53,256] [5028-MainProcess/4252-Thread-9] WARNING - SMARTCANTEEN shift_meal_serving_post() ConflictError-shift_meal_serving  with id = 3 is existing
[2020-02-06 19:27:48,075] [8424-MainProcess/5588-Thread-6] WARNING - SMARTCANTEEN require_authenticate() AuthenticateError-CommonLibError-Invalid Session Key
[2020-02-06 19:27:54,933] [8424-MainProcess/5032-Thread-8] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 19:35:26,016] [4312-MainProcess/7260-Thread-1] WARNING - SMARTCANTEEN require_authenticate() AuthenticateError-CommonLibError-Invalid Session Key
[2020-02-06 19:35:34,922] [4312-MainProcess/6772-Thread-2] INFO - SMARTCANTEEN login_post() Login succeeded, id=9999
[2020-02-06 19:35:41,118] [4312-MainProcess/5076-Thread-3] WARNING - SMARTCANTEEN shift_meal_serving_put() InvalidParamError-serving id = 4 is not existing
[2020-02-06 19:36:39,431] [4312-MainProcess/5516-Thread-5] ERROR - SMARTCANTEEN shift_meal_serving_put() error=New instance <MShiftMealServing at 0x133e33c2970> with identity key (<class 'commonlib.dbmodel.db_model.MShiftMealServing'>, (5,), None) conflicts with persistent instance <MShiftMealServing at 0x133e357bf70> tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 166, in __execute_shift_meal_serving_put\n    cls.__ensure_using_shift_meal_serving_(db, item.id)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 243, in __ensure_using_shift_meal_serving_\n    if LineShiftMealServingSql.is_shift_meal_serving_existing(db, id):\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\sql.py", line 1360, in is_shift_meal_serving_existing\n    ret = db.session.query(MLineShiftMealServing).filter(MLineShiftMealServing.shift_meal_serving_id == shift_meal_serving_id).first()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3265, in first\n    ret = list(self[0:1])\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3043, in __getitem__\n    return list(res)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3366, in __iter__\n    self.session._autoflush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1586, in _autoflush\n    self.flush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2479, in flush\n    self._flush(objects)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2577, in _flush\n    flush_context.execute()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 422, in execute\n    rec.execute(self)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 586, in execute\n    persistence.save_obj(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 205, in save_obj\n    for (\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 405, in _organize_states_for_save\n    raise orm_exc.FlushError(\n']
[2020-02-06 19:40:27,250] [10540-MainProcess/10720-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_put() error=list.remove(x): x not in list tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 151, in __execute_shift_meal_serving_put\n    list_serving.remove(item)\n']
[2020-02-06 19:43:21,312] [9944-MainProcess/7360-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_put() error='ServingInfo' object has no attribute 'serving_id' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 143, in __execute_shift_meal_serving_put\n    if serving.id == list_serving[idx].serving_id:\n']
[2020-02-06 19:44:58,913] [3448-MainProcess/9016-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_put() error='ServingInfo' object has no attribute 'serving_id' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 143, in __execute_shift_meal_serving_put\n    if serving.id == list_serving[idx].serving_id:\n']
[2020-02-06 19:46:38,222] [9328-MainProcess/900-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_put() error='ServingInfo' object has no attribute 'serving_id' tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 143, in __execute_shift_meal_serving_put\n    if serving.id == list_serving[idx].serving_id:\n']
[2020-02-06 19:51:25,632] [4272-MainProcess/6012-Thread-6] ERROR - SMARTCANTEEN shift_meal_serving_put() error=name 'shift_meal_list_serving' is not defined tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 166, in __execute_shift_meal_serving_put\n    for item in shift_meal_list_serving:\n']
[2020-02-06 19:51:52,290] [10600-MainProcess/3620-Thread-6] ERROR - SMARTCANTEEN shift_meal_serving_put() error=(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'serving_id', table 'SMARTCANTEEN.dbo.m_shift_meal_serving'; column does not allow nulls. INSERT fails. (515) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")
[SQL: INSERT INTO m_shift_meal_serving (id, shift_meal_id, serving_id, factory_id, created, modified, name, upd_count, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (5, 1, None, 1, None, None, 'factory1-shift1-START mealPho 1', None, None)]
(Background on this error at: http://sqlalche.me/e/gkpj) tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 168, in __execute_shift_meal_serving_put\n    cls.__ensure_using_shift_meal_serving_(db, item.id)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 245, in __ensure_using_shift_meal_serving_\n    if LineShiftMealServingSql.is_shift_meal_serving_existing(db, id):\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\sql.py", line 1360, in is_shift_meal_serving_existing\n    ret = db.session.query(MLineShiftMealServing).filter(MLineShiftMealServing.shift_meal_serving_id == shift_meal_serving_id).first()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3265, in first\n    ret = list(self[0:1])\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3043, in __getitem__\n    return list(res)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3366, in __iter__\n    self.session._autoflush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1597, in _autoflush\n    util.raise_from_cause(e)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1586, in _autoflush\n    self.flush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2479, in flush\n    self._flush(objects)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2577, in _flush\n    flush_context.execute()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 422, in execute\n    rec.execute(self)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 586, in execute\n    persistence.save_obj(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 1084, in _emit_insert_statements\n    c = cached_connections[connection].execute(statement, multiparams)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 982, in execute\n    return meth(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n']
[2020-02-06 19:52:12,383] [10388-MainProcess/2852-Thread-6] ERROR - SMARTCANTEEN shift_meal_serving_put() error=(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'serving_id', table 'SMARTCANTEEN.dbo.m_shift_meal_serving'; column does not allow nulls. INSERT fails. (515) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")
[SQL: INSERT INTO m_shift_meal_serving (id, shift_meal_id, serving_id, factory_id, created, modified, name, upd_count, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (5, 1, None, 1, None, None, 'factory1-shift1-START mealPho 1', None, None)]
(Background on this error at: http://sqlalche.me/e/gkpj) tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 168, in __execute_shift_meal_serving_put\n    cls.__ensure_using_shift_meal_serving_(db, item.id)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 245, in __ensure_using_shift_meal_serving_\n    if LineShiftMealServingSql.is_shift_meal_serving_existing(db, id):\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\sql.py", line 1360, in is_shift_meal_serving_existing\n    ret = db.session.query(MLineShiftMealServing).filter(MLineShiftMealServing.shift_meal_serving_id == shift_meal_serving_id).first()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3265, in first\n    ret = list(self[0:1])\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3043, in __getitem__\n    return list(res)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3366, in __iter__\n    self.session._autoflush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1597, in _autoflush\n    util.raise_from_cause(e)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1586, in _autoflush\n    self.flush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2479, in flush\n    self._flush(objects)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2577, in _flush\n    flush_context.execute()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 422, in execute\n    rec.execute(self)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 586, in execute\n    persistence.save_obj(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 1084, in _emit_insert_statements\n    c = cached_connections[connection].execute(statement, multiparams)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 982, in execute\n    return meth(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n']
[2020-02-06 19:55:29,672] [2852-MainProcess/5388-Thread-1] ERROR - SMARTCANTEEN shift_meal_serving_put() error=(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'serving_id', table 'SMARTCANTEEN.dbo.m_shift_meal_serving'; column does not allow nulls. INSERT fails. (515) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")
[SQL: INSERT INTO m_shift_meal_serving (id, shift_meal_id, serving_id, factory_id, created, modified, name, upd_count, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (5, 1, None, 1, None, None, 'factory1-shift1-START mealPho 1', None, None)]
(Background on this error at: http://sqlalche.me/e/gkpj) tb=['  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\common.py", line 36, in system_error_handler\n    return f(*args, **kwargs)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 122, in shift_meal_serving_put\n    cls.__execute_shift_meal_serving_put(db, shift_meal_serving_edit)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 168, in __execute_shift_meal_serving_put\n    cls.__ensure_using_shift_meal_serving_(db, item.id)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\logic\\shift_meal_serving_logic.py", line 245, in __ensure_using_shift_meal_serving_\n    if LineShiftMealServingSql.is_shift_meal_serving_existing(db, id):\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\smartcanteen\\util\\sql.py", line 1360, in is_shift_meal_serving_existing\n    ret = db.session.query(MLineShiftMealServing).filter(MLineShiftMealServing.shift_meal_serving_id == shift_meal_serving_id).first()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3265, in first\n    ret = list(self[0:1])\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3043, in __getitem__\n    return list(res)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py", line 3366, in __iter__\n    self.session._autoflush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1597, in _autoflush\n    util.raise_from_cause(e)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1586, in _autoflush\n    self.flush()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2479, in flush\n    self._flush(objects)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 153, in reraise\n    raise value\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2577, in _flush\n    flush_context.execute()\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 422, in execute\n    rec.execute(self)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 586, in execute\n    persistence.save_obj(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 1084, in _emit_insert_statements\n    c = cached_connections[connection].execute(statement, multiparams)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 982, in execute\n    return meth(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\util\\compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n', '  File "D:\\NIDEC\\_git\\nidec_canteen\\30_src\\20_web\\server\\venv\\lib\\site-packages\\sqlalchemy\\engine\\default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n']
[2020-02-06 19:58:55,362] [11092-MainProcess/11016-Thread-1] WARNING - SMARTCANTEEN shift_meal_serving_put() ConflictError-shift_meal_id = 3 is being used line_shift_meal_serving table
[2020-02-06 20:09:56,977] [9240-MainProcess/7700-Thread-1] WARNING - SMARTCANTEEN shift_meal_serving_put() ConflictError-shift_meal_id = 3 is being used line_shift_meal_serving table
[2020-02-06 20:16:42,798] [2080-MainProcess/11252-Thread-1] WARNING - SMARTCANTEEN shift_meal_serving_put() ConflictError-shift_meal_id = 3 is being used line_shift_meal_serving table
